### ISSUE TITLE
Making => moveable

### ISSUE THREAD

**Issue by gsabater** [bladnman/auto-align#1]
Hello Matt,

I have been trying your extension, and i have to say that it looks pretty good.
The thing I have found is that i would like to configure multidimensional arrays in php to be aligned, eg:
```
$arr = [
    "name" => "one",
    "title" => "two",
    "path" => "three"
],
```
Adding  `=>` to `"autoalign.moveableItems"` has no effect, and the array is not aligned. I know that there is a `"autoalign.nonMoveableItems"` option, and copying the whole array to the settings make the operator movable.

Maybe you should make a third option that prevents users to copy a 50 line array to their user settings, and also, when i align that array, what i get is a broken operator with an extra space between the = and > 

```
$arr = [
    "name"    = > "one",
    "title"   = > "two",
    "path"    = > "three"
],
```

Thanks

**Comment by bladnman** [comment]
yeah... interesting. That's ugly. Feels like there are 2 issues at play here. 1 is that if something is found in moveable and non-moveable the `non` wins. The other is once you remove it from the non-list then the aligner finds the *first* moveable item in the list (in this case the `=`). I can see a way to solve both of these. I will look into it, thanks!

**Comment by bladnman** [comment]
This has been patched. Thanks for the heads-up.

**Comment by gsabater** [comment]
The extension works perfectly, thanks a lot for your work.
