### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by kiwicopple** [bladnman/auto-align#3]
Not an issue per se, I just wanted to let you know that I'm using your plugin and I love it.

Thank you

**Comment by kiwicopple** [comment]
Feel free to close

**Comment by kiwicopple** [comment]
Actually I do have one question. Do you use [Prettier](https://prettier.io/), and if you do how do you configure these extensions to work together?

**Comment by kiwicopple** [comment]
It looks like this will be very hard. See [here](https://github.com/prettier/prettier/issues/5770), [here](https://github.com/prettier/prettier/issues/188), [here](https://github.com/prettier/prettier/issues/1622).

There is a [prettier-miscellaneous](https://github.com/arijs/prettier-miscellaneous) package that has an option for Object Properties, but it [looks like they aren't going to support variable vertical assignments](https://github.com/prettier/prettier/issues/1622#issuecomment-307798939).

Annoyingly, prettier doesn't seem to have `prettier-ignore` *ranges* for JS files, so I guess it's a tradeoff between prettier and alignment ¯\_(ツ)_/¯

**Comment by bladnman** [comment]
Sorry kiwi! Just seeing these notes. Yeah, this stuff just fights with Prettier. In the end this can be useful to align things during editing and prettier takes care of things during committing. 

This depends on a LOT of things, though.
